import { CatalogRetailerSource } from "@/lib/catalog-db";

export const catalogSources: CatalogRetailerSource[] = [
  {
    id: "walmart",
    name: "Walmart",
    url: "https://www.walmart.com/cp/food/976759",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
    notes: "Large public catalog, but prices and assortment are location-sensitive.",
  },
  {
    id: "target",
    name: "Target",
    url: "https://www.target.com/c/grocery/-/N-5xt1a",
    region: "national",
    tier: "official_site",
    accessMode: "store_required",
    notes: "Online and in-store pricing can differ by store.",
  },
  {
    id: "amazon-fresh",
    name: "Amazon Fresh",
    url: "https://www.amazon.com/alm/storefront",
    region: "national",
    tier: "official_site",
    accessMode: "login_required",
    notes: "Account and delivery-area context usually required.",
  },
  {
    id: "costco",
    name: "Costco",
    url: "https://www.costco.com/grocery-household.html",
    region: "national",
    tier: "marketplace",
    accessMode: "zip_required",
    notes: "Assortment and pricing vary; same-day storefront often differs from warehouse.",
  },
  {
    id: "sams-club",
    name: "Sam's Club",
    url: "https://www.samsclub.com/c/grocery/1444",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "kroger",
    name: "Kroger",
    url: "https://www.kroger.com/",
    region: "national",
    tier: "official_api",
    accessMode: "store_required",
    notes: "Best first-party pricing path for this repo.",
  },
  {
    id: "albertsons",
    name: "Albertsons",
    url: "https://www.albertsons.com/shop.html",
    region: "national",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "safeway",
    name: "Safeway",
    url: "https://www.safeway.com/shop.html",
    region: "national",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "vons",
    name: "Vons",
    url: "https://www.vons.com/shop.html",
    region: "national",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "jewel-osco",
    name: "Jewel-Osco",
    url: "https://www.jewelosco.com/shop.html",
    region: "national",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "publix",
    name: "Publix",
    url: "https://www.publix.com/shop-online",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "aldi",
    name: "ALDI",
    url: "https://shop.aldi.us/",
    region: "national",
    tier: "marketplace",
    accessMode: "zip_required",
  },
  {
    id: "whole-foods",
    name: "Whole Foods Market",
    url: "https://www.wholefoodsmarket.com/",
    region: "national",
    tier: "official_site",
    accessMode: "login_required",
    notes: "Grocery delivery and pickup route through Amazon account context.",
  },
  {
    id: "trader-joes",
    name: "Trader Joe's",
    url: "https://www.traderjoes.com/home/products",
    region: "national",
    tier: "official_site",
    accessMode: "public_browse",
    notes: "Good for product discovery, not comprehensive online pricing.",
  },
  {
    id: "wegmans",
    name: "Wegmans",
    url: "https://shop.wegmans.com/",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "meijer",
    name: "Meijer",
    url: "https://www.meijer.com/shopping/grocery.html",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "hy-vee",
    name: "Hy-Vee",
    url: "https://www.hy-vee.com/grocery/",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "winco",
    name: "WinCo Foods",
    url: "https://www.wincofoods.com/",
    region: "national",
    tier: "official_site",
    accessMode: "public_browse",
  },
  {
    id: "heb",
    name: "H-E-B",
    url: "https://www.heb.com/",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "food-lion",
    name: "Food Lion",
    url: "https://shop.foodlion.com/",
    region: "national",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "giant-food",
    name: "Giant Food",
    url: "https://giantfood.com/shop-online/",
    region: "regional",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "giant-eagle",
    name: "Giant Eagle",
    url: "https://www.gianteagle.com/shop-online",
    region: "regional",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "stop-shop",
    name: "Stop & Shop",
    url: "https://stopandshop.com/",
    region: "regional",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "shoprite",
    name: "ShopRite",
    url: "https://www.shoprite.com/",
    region: "regional",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "harris-teeter",
    name: "Harris Teeter",
    url: "https://www.harristeeter.com/",
    region: "regional",
    tier: "official_api",
    accessMode: "store_required",
  },
  {
    id: "raleys",
    name: "Raley's",
    url: "https://www.raleys.com/",
    region: "regional",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "save-mart",
    name: "Save Mart",
    url: "https://www.savemart.com/shop",
    region: "regional",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "lucky",
    name: "Lucky Supermarkets",
    url: "https://www.luckysupermarkets.com/shop",
    region: "regional",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "cub",
    name: "Cub Foods",
    url: "https://www.cub.com/shop",
    region: "regional",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "bashas",
    name: "Bashas'",
    url: "https://www.bashas.com/shop/",
    region: "regional",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "frys-food",
    name: "Fry's Food",
    url: "https://www.frysfood.com/",
    region: "regional",
    tier: "official_api",
    accessMode: "store_required",
  },
  {
    id: "king-soopers",
    name: "King Soopers",
    url: "https://www.kingsoopers.com/",
    region: "regional",
    tier: "official_api",
    accessMode: "store_required",
  },
  {
    id: "fred-meyer",
    name: "Fred Meyer",
    url: "https://www.fredmeyer.com/",
    region: "regional",
    tier: "official_api",
    accessMode: "store_required",
  },
  {
    id: "qfc",
    name: "QFC",
    url: "https://www.qfc.com/",
    region: "regional",
    tier: "official_api",
    accessMode: "store_required",
  },
  {
    id: "pavilions",
    name: "Pavilions",
    url: "https://www.pavilions.com/shop.html",
    region: "regional",
    tier: "official_site",
    accessMode: "store_required",
  },
  {
    id: "instacart",
    name: "Instacart",
    url: "https://www.instacart.com/",
    region: "online-first",
    tier: "marketplace",
    accessMode: "zip_required",
    notes: "Marketplace pricing and availability vary by retailer and location.",
  },
  {
    id: "shipt",
    name: "Shipt",
    url: "https://www.shipt.com/",
    region: "online-first",
    tier: "marketplace",
    accessMode: "login_required",
  },
  {
    id: "amazon-grocery",
    name: "Amazon Grocery",
    url: "https://www.amazon.com/grocery-store",
    region: "online-first",
    tier: "marketplace",
    accessMode: "login_required",
  },
  {
    id: "freshdirect",
    name: "FreshDirect",
    url: "https://www.freshdirect.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "thrive-market",
    name: "Thrive Market",
    url: "https://thrivemarket.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "login_required",
  },
  {
    id: "misfits-market",
    name: "Misfits Market",
    url: "https://www.misfitsmarket.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "login_required",
  },
  {
    id: "imperfect-foods",
    name: "Imperfect Foods",
    url: "https://www.imperfectfoods.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "boxed",
    name: "Boxed",
    url: "https://www.boxed.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "login_required",
  },
  {
    id: "gopuff",
    name: "GoPuff",
    url: "https://www.gopuff.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "weee",
    name: "Weee!",
    url: "https://www.sayweee.com/",
    region: "online-first",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "azure-standard",
    name: "Azure Standard",
    url: "https://www.azurestandard.com/",
    region: "specialty",
    tier: "official_site",
    accessMode: "public_browse",
  },
  {
    id: "umamicart",
    name: "Umamicart",
    url: "https://www.umamicart.com/",
    region: "specialty",
    tier: "official_site",
    accessMode: "zip_required",
  },
  {
    id: "hungryroot",
    name: "Hungryroot",
    url: "https://www.hungryroot.com/",
    region: "specialty",
    tier: "official_site",
    accessMode: "login_required",
  },
  {
    id: "vitacost",
    name: "Vitacost",
    url: "https://www.vitacost.com/",
    region: "specialty",
    tier: "official_site",
    accessMode: "public_browse",
  },
  {
    id: "iherb",
    name: "iHerb",
    url: "https://www.iherb.com/",
    region: "specialty",
    tier: "official_site",
    accessMode: "public_browse",
  },
];
