import { PricingRule, Product, Store } from "@/lib/types";

export const stores: Store[] = [
  {
    id: "qfc-ballard",
    chain: "QFC",
    name: "QFC Ballard",
    address: "5700 24th Ave NW, Seattle, WA 98107",
    coordinates: { lat: 47.6699, lng: -122.3872 },
    timezone: "America/Los_Angeles",
    supportsPricing: true,
    placeId: "qfc-ballard-place",
    hours: {
      sunday: [{ start: "06:00", end: "23:00" }],
      monday: [{ start: "06:00", end: "23:00" }],
      tuesday: [{ start: "06:00", end: "23:00" }],
      wednesday: [{ start: "06:00", end: "23:00" }],
      thursday: [{ start: "06:00", end: "23:00" }],
      friday: [{ start: "06:00", end: "23:00" }],
      saturday: [{ start: "06:00", end: "23:00" }],
    },
  },
  {
    id: "fred-meyer-ballard",
    chain: "Fred Meyer",
    name: "Fred Meyer Ballard",
    address: "915 NW 45th St, Seattle, WA 98107",
    coordinates: { lat: 47.6617, lng: -122.3696 },
    timezone: "America/Los_Angeles",
    supportsPricing: true,
    placeId: "fred-meyer-ballard-place",
    hours: {
      sunday: [{ start: "06:00", end: "22:00" }],
      monday: [{ start: "06:00", end: "22:00" }],
      tuesday: [{ start: "06:00", end: "22:00" }],
      wednesday: [{ start: "06:00", end: "22:00" }],
      thursday: [{ start: "06:00", end: "22:00" }],
      friday: [{ start: "06:00", end: "22:00" }],
      saturday: [{ start: "06:00", end: "22:00" }],
    },
  },
  {
    id: "safeway-crown-hill",
    chain: "Safeway",
    name: "Safeway Crown Hill",
    address: "8340 15th Ave NW, Seattle, WA 98117",
    coordinates: { lat: 47.6915, lng: -122.3767 },
    timezone: "America/Los_Angeles",
    supportsPricing: false,
    placeId: "safeway-crown-hill-place",
    hours: {
      sunday: [{ start: "05:00", end: "01:00" }],
      monday: [{ start: "05:00", end: "01:00" }],
      tuesday: [{ start: "05:00", end: "01:00" }],
      wednesday: [{ start: "05:00", end: "01:00" }],
      thursday: [{ start: "05:00", end: "01:00" }],
      friday: [{ start: "05:00", end: "01:00" }],
      saturday: [{ start: "05:00", end: "01:00" }],
    },
  },
];

type SeedProduct = Omit<Product, "id" | "price" | "sku" | "storeId"> & {
  key: string;
  basePrice: number;
  priceOverrides?: Partial<Record<Store["id"], number>>;
  stores?: Store["id"][];
};

const seededCatalog: SeedProduct[] = [
  {
    key: "ben-jerrys-cherry-garcia",
    brand: "Ben & Jerry's",
    name: "Cherry Garcia Ice Cream",
    normalizedName: "ben and jerrys cherry garcia ice cream pint",
    searchAliases: ["ben and jerry's", "ben and jerrys", "cherry garcia", "ice cream pint"],
    category: "ice-cream",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "haagen-dazs-vanilla",
    brand: "Haagen-Dazs",
    name: "Vanilla Ice Cream",
    normalizedName: "haagen dazs vanilla ice cream pint",
    searchAliases: ["haagen dazs", "haagen-dazs", "vanilla ice cream"],
    category: "ice-cream",
    sizeValue: 14,
    sizeUnit: "oz",
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "ben-jerrys-chocolate-fudge-brownie",
    brand: "Ben & Jerry's",
    name: "Chocolate Fudge Brownie Ice Cream",
    normalizedName: "ben and jerrys chocolate fudge brownie ice cream pint",
    searchAliases: [
      "ben and jerry's chocolate",
      "ben and jerrys chocolate",
      "chocolate ice cream",
      "fudge brownie ice cream",
      "brownie ice cream",
    ],
    category: "ice-cream",
    variant: "chocolate fudge brownie",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "ben-jerrys-chocolate-chip-cookie-dough",
    brand: "Ben & Jerry's",
    name: "Chocolate Chip Cookie Dough Ice Cream",
    normalizedName: "ben and jerrys chocolate chip cookie dough ice cream pint",
    searchAliases: [
      "cookie dough ice cream",
      "chocolate chip cookie dough",
      "ben and jerry's cookie dough",
      "ben and jerrys cookie dough",
    ],
    category: "ice-cream",
    variant: "chocolate chip cookie dough",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "ben-jerrys-half-baked",
    brand: "Ben & Jerry's",
    name: "Half Baked Ice Cream",
    normalizedName: "ben and jerrys half baked ice cream pint",
    searchAliases: [
      "half baked",
      "cookie dough brownie ice cream",
      "chocolate and vanilla ice cream",
    ],
    category: "ice-cream",
    variant: "cookie dough brownie",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "haagen-dazs-chocolate",
    brand: "Haagen-Dazs",
    name: "Chocolate Ice Cream",
    normalizedName: "haagen dazs chocolate ice cream pint",
    searchAliases: ["haagen dazs chocolate", "haagen-dazs chocolate", "chocolate ice cream pint"],
    category: "ice-cream",
    variant: "chocolate",
    sizeValue: 14,
    sizeUnit: "oz",
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "haagen-dazs-coffee",
    brand: "Haagen-Dazs",
    name: "Coffee Ice Cream",
    normalizedName: "haagen dazs coffee ice cream pint",
    searchAliases: ["coffee ice cream", "haagen dazs coffee", "haagen-dazs coffee"],
    category: "ice-cream",
    variant: "coffee",
    sizeValue: 14,
    sizeUnit: "oz",
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "haagen-dazs-butter-pecan",
    brand: "Haagen-Dazs",
    name: "Butter Pecan Ice Cream",
    normalizedName: "haagen dazs butter pecan ice cream pint",
    searchAliases: ["butter pecan ice cream", "haagen dazs butter pecan", "pecan ice cream"],
    category: "ice-cream",
    variant: "butter pecan",
    sizeValue: 14,
    sizeUnit: "oz",
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "talenti-double-dark-chocolate",
    brand: "Talenti",
    name: "Double Dark Chocolate Gelato",
    normalizedName: "talenti double dark chocolate gelato pint",
    searchAliases: ["talenti chocolate", "double dark chocolate", "chocolate gelato", "gelato"],
    category: "ice-cream",
    variant: "double dark chocolate",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 6.29,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "talenti-vanilla-caramel-swirl",
    brand: "Talenti",
    name: "Vanilla Caramel Swirl Gelato",
    normalizedName: "talenti vanilla caramel swirl gelato pint",
    searchAliases: ["talenti vanilla", "vanilla gelato", "caramel swirl ice cream"],
    category: "ice-cream",
    variant: "vanilla caramel swirl",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 6.29,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "tillamook-mudslide",
    brand: "Tillamook",
    name: "Mudslide Ice Cream",
    normalizedName: "tillamook mudslide ice cream 48 oz",
    searchAliases: ["tillamook chocolate", "mudslide", "chocolate ice cream tub", "family size ice cream"],
    category: "ice-cream",
    variant: "mudslide",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 6.99,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "tillamook-old-fashioned-vanilla",
    brand: "Tillamook",
    name: "Old-Fashioned Vanilla Ice Cream",
    normalizedName: "tillamook old fashioned vanilla ice cream 48 oz",
    searchAliases: ["tillamook vanilla", "vanilla ice cream tub", "old fashioned vanilla"],
    category: "ice-cream",
    variant: "vanilla",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 6.99,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "tillamook-chocolate-peanut-butter",
    brand: "Tillamook",
    name: "Chocolate Peanut Butter Ice Cream",
    normalizedName: "tillamook chocolate peanut butter ice cream 48 oz",
    searchAliases: ["chocolate peanut butter ice cream", "tillamook chocolate peanut butter", "peanut butter ice cream"],
    category: "ice-cream",
    variant: "chocolate peanut butter",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 6.99,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "breyers-chocolate",
    brand: "Breyers",
    name: "Chocolate Ice Cream",
    normalizedName: "breyers chocolate ice cream 48 oz",
    searchAliases: ["breyers chocolate", "chocolate ice cream", "chocolate ice cream tub"],
    category: "ice-cream",
    variant: "chocolate",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 5.79,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "breyers-natural-vanilla",
    brand: "Breyers",
    name: "Natural Vanilla Ice Cream",
    normalizedName: "breyers natural vanilla ice cream 48 oz",
    searchAliases: ["breyers vanilla", "vanilla ice cream", "natural vanilla ice cream"],
    category: "ice-cream",
    variant: "vanilla",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 5.79,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "breyers-cookies-cream",
    brand: "Breyers",
    name: "Cookies & Cream Ice Cream",
    normalizedName: "breyers cookies and cream ice cream 48 oz",
    searchAliases: ["cookies and cream", "cookies & cream", "breyers cookies and cream", "oreo ice cream"],
    category: "ice-cream",
    variant: "cookies and cream",
    sizeValue: 48,
    sizeUnit: "oz",
    basePrice: 5.79,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "oreo-frozen-dessert-bars",
    brand: "Oreo",
    name: "Frozen Dairy Dessert Bars",
    normalizedName: "oreo frozen dairy dessert bars 5 count",
    searchAliases: ["oreo ice cream bars", "oreo frozen dessert", "ice cream bars"],
    category: "ice-cream",
    variant: "oreo bars",
    sizeValue: 5,
    sizeUnit: "ct",
    packageCount: 5,
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.6,
  },
  {
    key: "drumstick-vanilla-fudge",
    brand: "Drumstick",
    name: "Vanilla Fudge Dipped Sundae Cones",
    normalizedName: "drumstick vanilla fudge dipped sundae cones 8 count",
    searchAliases: ["drumstick ice cream", "sundae cones", "ice cream cones", "vanilla fudge cones"],
    category: "ice-cream",
    variant: "vanilla fudge",
    sizeValue: 8,
    sizeUnit: "ct",
    packageCount: 8,
    basePrice: 7.29,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "coke-classic-12pk",
    brand: "Coca-Cola",
    name: "Coca-Cola Classic 12 Pack",
    normalizedName: "coca cola classic 12 pack 12 oz",
    searchAliases: ["coke", "coca cola", "cola 12 pack", "soda"],
    category: "beverages",
    sizeValue: 12,
    sizeUnit: "oz",
    packageCount: 12,
    basePrice: 8.99,
    taxable: true,
    beverageTaxable: true,
    bagUnits: 1.25,
  },
  {
    key: "coke-zero-12pk",
    brand: "Coca-Cola",
    name: "Coke Zero 12 Pack",
    normalizedName: "coke zero 12 pack 12 oz",
    searchAliases: ["coke zero", "zero sugar coke", "coca cola zero"],
    category: "beverages",
    variant: "zero sugar",
    sizeValue: 12,
    sizeUnit: "oz",
    packageCount: 12,
    basePrice: 8.99,
    taxable: true,
    beverageTaxable: false,
    bagUnits: 1.25,
  },
  {
    key: "pepsi-12pk",
    brand: "Pepsi",
    name: "Pepsi Cola 12 Pack",
    normalizedName: "pepsi cola 12 pack 12 oz",
    searchAliases: ["pepsi", "pepsi cola", "cola 12 pack"],
    category: "beverages",
    sizeValue: 12,
    sizeUnit: "oz",
    packageCount: 12,
    basePrice: 8.79,
    taxable: true,
    beverageTaxable: true,
    bagUnits: 1.25,
  },
  {
    key: "gatorade-lemon-lime-8pk",
    brand: "Gatorade",
    name: "Lemon-Lime Sports Drink 8 Pack",
    normalizedName: "gatorade lemon lime sports drink 20 oz 8 pack",
    searchAliases: ["gatorade", "sports drink", "lemon lime gatorade"],
    category: "beverages",
    sizeValue: 20,
    sizeUnit: "oz",
    packageCount: 8,
    basePrice: 8.49,
    taxable: true,
    beverageTaxable: true,
    bagUnits: 1,
  },
  {
    key: "tropicana-orange-juice",
    brand: "Tropicana",
    name: "Original Orange Juice",
    normalizedName: "tropicana original orange juice 52 oz",
    searchAliases: ["orange juice", "tropicana oj"],
    category: "juice",
    sizeValue: 52,
    sizeUnit: "oz",
    basePrice: 4.69,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "fairlife-milk-2",
    brand: "fairlife",
    name: "2% Ultra-Filtered Milk",
    normalizedName: "fairlife 2 percent ultra filtered milk 52 oz",
    searchAliases: ["fairlife milk", "2% milk", "2 percent milk"],
    category: "dairy",
    variant: "2%",
    sizeValue: 52,
    sizeUnit: "oz",
    basePrice: 4.99,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "land-o-lakes-butter",
    brand: "Land O Lakes",
    name: "Salted Butter",
    normalizedName: "land o lakes salted butter 16 oz",
    searchAliases: ["butter", "salted butter"],
    category: "dairy",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.29,
    taxable: false,
    bagUnits: 0.25,
  },
  {
    key: "eggs-large-dozen",
    brand: "Eggland's Best",
    name: "Large Eggs 12 Count",
    normalizedName: "egglands best large eggs dozen 12 count",
    searchAliases: ["eggs", "large eggs", "dozen eggs"],
    category: "eggs",
    sizeValue: 12,
    sizeUnit: "ct",
    packageCount: 12,
    basePrice: 4.29,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "chobani-greek-yogurt-strawberry",
    brand: "Chobani",
    name: "Strawberry Greek Yogurt",
    normalizedName: "chobani strawberry greek yogurt 5.3 oz",
    searchAliases: ["chobani yogurt", "greek yogurt", "strawberry yogurt"],
    category: "yogurt",
    sizeValue: 5.3,
    sizeUnit: "oz",
    basePrice: 1.79,
    taxable: false,
    bagUnits: 0.2,
  },
  {
    key: "cheerios-family-size",
    brand: "Cheerios",
    name: "Original Family Size Cereal",
    normalizedName: "cheerios original family size cereal 18 oz",
    searchAliases: ["cheerios", "cereal", "original cheerios"],
    category: "cereal",
    sizeValue: 18,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: true,
    bagUnits: 0.8,
  },
  {
    key: "frosted-flakes",
    brand: "Kellogg's",
    name: "Frosted Flakes Cereal",
    normalizedName: "kelloggs frosted flakes cereal 16.3 oz",
    searchAliases: ["frosted flakes", "kelloggs cereal"],
    category: "cereal",
    sizeValue: 16.3,
    sizeUnit: "oz",
    basePrice: 5.69,
    taxable: true,
    bagUnits: 0.8,
  },
  {
    key: "wonder-bread",
    brand: "Wonder",
    name: "Classic White Bread",
    normalizedName: "wonder classic white bread 20 oz",
    searchAliases: ["wonder bread", "white bread", "bread loaf"],
    category: "bakery",
    sizeValue: 20,
    sizeUnit: "oz",
    basePrice: 3.49,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "nature-valley-bars",
    brand: "Nature Valley",
    name: "Crunchy Oats 'n Honey Granola Bars",
    normalizedName: "nature valley crunchy oats n honey granola bars 12 ct",
    searchAliases: ["granola bars", "nature valley bars", "oats and honey"],
    category: "snacks",
    sizeValue: 12,
    sizeUnit: "ct",
    packageCount: 12,
    basePrice: 4.69,
    taxable: true,
    bagUnits: 0.6,
  },
  {
    key: "lays-classic",
    brand: "Lay's",
    name: "Classic Potato Chips",
    normalizedName: "lays classic potato chips 8 oz",
    searchAliases: ["lays chips", "potato chips", "chips"],
    category: "snacks",
    sizeValue: 8,
    sizeUnit: "oz",
    basePrice: 4.79,
    taxable: true,
    bagUnits: 0.5,
  },
  {
    key: "doritos-nacho",
    brand: "Doritos",
    name: "Nacho Cheese Tortilla Chips",
    normalizedName: "doritos nacho cheese tortilla chips 9.25 oz",
    searchAliases: ["doritos", "nacho cheese chips", "tortilla chips"],
    category: "snacks",
    sizeValue: 9.25,
    sizeUnit: "oz",
    basePrice: 5.29,
    taxable: true,
    bagUnits: 0.5,
  },
  {
    key: "oreo-family-size",
    brand: "Oreo",
    name: "Original Family Size Cookies",
    normalizedName: "oreo original family size cookies 18.12 oz",
    searchAliases: ["oreo", "cookies", "oreo family size"],
    category: "cookies",
    sizeValue: 18.12,
    sizeUnit: "oz",
    basePrice: 5.19,
    taxable: true,
    bagUnits: 0.5,
  },
  {
    key: "ritz-crackers",
    brand: "Ritz",
    name: "Original Crackers",
    normalizedName: "ritz original crackers 13.7 oz",
    searchAliases: ["ritz", "crackers", "ritz crackers"],
    category: "crackers",
    sizeValue: 13.7,
    sizeUnit: "oz",
    basePrice: 4.39,
    taxable: true,
    bagUnits: 0.5,
  },
  {
    key: "jif-peanut-butter",
    brand: "Jif",
    name: "Creamy Peanut Butter",
    normalizedName: "jif creamy peanut butter 28 oz",
    searchAliases: ["jif", "peanut butter", "creamy peanut butter"],
    category: "pantry",
    sizeValue: 28,
    sizeUnit: "oz",
    basePrice: 4.99,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "smuckers-strawberry-jam",
    brand: "Smucker's",
    name: "Strawberry Jam",
    normalizedName: "smuckers strawberry jam 32 oz",
    searchAliases: ["jam", "strawberry jam", "smuckers jelly"],
    category: "pantry",
    sizeValue: 32,
    sizeUnit: "oz",
    basePrice: 5.29,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "kraft-mac-cheese",
    brand: "Kraft",
    name: "Original Mac & Cheese Dinner",
    normalizedName: "kraft original mac and cheese dinner 7.25 oz",
    searchAliases: ["kraft mac and cheese", "mac and cheese", "mac & cheese"],
    category: "boxed-meals",
    sizeValue: 7.25,
    sizeUnit: "oz",
    basePrice: 1.99,
    taxable: false,
    bagUnits: 0.2,
  },
  {
    key: "barilla-spaghetti",
    brand: "Barilla",
    name: "Spaghetti Pasta",
    normalizedName: "barilla spaghetti pasta 16 oz",
    searchAliases: ["spaghetti", "pasta", "barilla spaghetti"],
    category: "pasta",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 2.19,
    taxable: false,
    bagUnits: 0.25,
  },
  {
    key: "classico-marinara",
    brand: "Classico",
    name: "Traditional Sweet Basil Marinara",
    normalizedName: "classico traditional sweet basil marinara 24 oz",
    searchAliases: ["pasta sauce", "marinara", "classico sauce"],
    category: "pasta-sauce",
    sizeValue: 24,
    sizeUnit: "oz",
    basePrice: 3.79,
    taxable: false,
    bagUnits: 0.5,
  },
  {
    key: "campbells-chicken-noodle",
    brand: "Campbell's",
    name: "Chicken Noodle Soup",
    normalizedName: "campbells chicken noodle soup 10.75 oz",
    searchAliases: ["campbells soup", "chicken noodle soup", "soup can"],
    category: "soup",
    sizeValue: 10.75,
    sizeUnit: "oz",
    basePrice: 2.29,
    taxable: false,
    bagUnits: 0.25,
  },
  {
    key: "heinz-ketchup",
    brand: "Heinz",
    name: "Tomato Ketchup",
    normalizedName: "heinz tomato ketchup 32 oz",
    searchAliases: ["ketchup", "heinz ketchup"],
    category: "condiments",
    sizeValue: 32,
    sizeUnit: "oz",
    basePrice: 4.49,
    taxable: false,
    bagUnits: 0.35,
  },
  {
    key: "hellmanns-mayo",
    brand: "Hellmann's",
    name: "Real Mayonnaise",
    normalizedName: "hellmanns real mayonnaise 30 oz",
    searchAliases: ["mayo", "mayonnaise", "hellmanns mayo"],
    category: "condiments",
    sizeValue: 30,
    sizeUnit: "oz",
    basePrice: 5.99,
    taxable: false,
    bagUnits: 0.35,
  },
  {
    key: "hunts-tomatoes",
    brand: "Hunt's",
    name: "Diced Tomatoes",
    normalizedName: "hunts diced tomatoes 14.5 oz",
    searchAliases: ["diced tomatoes", "canned tomatoes", "tomatoes can"],
    category: "canned-goods",
    sizeValue: 14.5,
    sizeUnit: "oz",
    basePrice: 2.09,
    taxable: false,
    bagUnits: 0.25,
  },
  {
    key: "bananas",
    brand: "Fresh",
    name: "Bananas",
    normalizedName: "bananas",
    searchAliases: ["banana", "fresh bananas"],
    category: "produce",
    sizeValue: 1,
    sizeUnit: "lb",
    basePrice: 0.79,
    taxable: false,
    bagUnits: 0.25,
  },
  {
    key: "driscolls-strawberries",
    brand: "Driscoll's",
    name: "Strawberries",
    normalizedName: "driscolls strawberries 16 oz",
    searchAliases: ["strawberries", "berries", "driscolls berries"],
    category: "produce",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 4.49,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "dole-salad-kit",
    brand: "Dole",
    name: "Caesar Chopped Salad Kit",
    normalizedName: "dole caesar chopped salad kit 11.3 oz",
    searchAliases: ["salad kit", "caesar salad", "dole salad"],
    category: "produce",
    sizeValue: 11.3,
    sizeUnit: "oz",
    basePrice: 4.29,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "tyson-chicken-breast",
    brand: "Tyson",
    name: "Boneless Skinless Chicken Breast",
    normalizedName: "tyson boneless skinless chicken breast 2 lb",
    searchAliases: ["chicken breast", "tyson chicken", "boneless chicken"],
    category: "meat",
    sizeValue: 2,
    sizeUnit: "lb",
    basePrice: 11.99,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "oscar-mayer-bacon",
    brand: "Oscar Mayer",
    name: "Original Bacon",
    normalizedName: "oscar mayer original bacon 16 oz",
    searchAliases: ["bacon", "oscar mayer bacon"],
    category: "meat",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 7.49,
    taxable: false,
    bagUnits: 0.4,
  },
  {
    key: "jimmy-dean-sausage",
    brand: "Jimmy Dean",
    name: "Original Pork Sausage Roll",
    normalizedName: "jimmy dean original pork sausage roll 16 oz",
    searchAliases: ["sausage", "pork sausage", "jimmy dean"],
    category: "meat",
    sizeValue: 16,
    sizeUnit: "oz",
    basePrice: 5.49,
    taxable: false,
    bagUnits: 0.35,
  },
  {
    key: "digiorno-pepperoni",
    brand: "DiGiorno",
    name: "Rising Crust Pepperoni Pizza",
    normalizedName: "digiorno rising crust pepperoni pizza 27.1 oz",
    searchAliases: ["frozen pizza", "pepperoni pizza", "digiorno pizza"],
    category: "frozen",
    sizeValue: 27.1,
    sizeUnit: "oz",
    basePrice: 8.99,
    taxable: false,
    bagUnits: 0.7,
  },
  {
    key: "stouffers-lasagna",
    brand: "Stouffer's",
    name: "Family Size Lasagna",
    normalizedName: "stouffers family size lasagna 38 oz",
    searchAliases: ["frozen lasagna", "stouffers lasagna"],
    category: "frozen",
    sizeValue: 38,
    sizeUnit: "oz",
    basePrice: 10.99,
    taxable: false,
    bagUnits: 0.8,
  },
  {
    key: "eggo-waffles",
    brand: "Eggo",
    name: "Homestyle Waffles",
    normalizedName: "eggo homestyle waffles 24 ct",
    searchAliases: ["eggo waffles", "waffles", "frozen waffles"],
    category: "breakfast-frozen",
    sizeValue: 24,
    sizeUnit: "ct",
    packageCount: 24,
    basePrice: 5.79,
    taxable: false,
    bagUnits: 0.6,
  },
  {
    key: "starbucks-coffee",
    brand: "Starbucks",
    name: "Pike Place Roast Ground Coffee",
    normalizedName: "starbucks pike place roast ground coffee 28 oz",
    searchAliases: ["coffee", "ground coffee", "starbucks coffee"],
    category: "coffee",
    sizeValue: 28,
    sizeUnit: "oz",
    basePrice: 12.99,
    taxable: false,
    bagUnits: 0.35,
  },
  {
    key: "folgers-coffee",
    brand: "Folgers",
    name: "Classic Roast Ground Coffee",
    normalizedName: "folgers classic roast ground coffee 25.9 oz",
    searchAliases: ["folgers", "coffee tub", "ground coffee"],
    category: "coffee",
    sizeValue: 25.9,
    sizeUnit: "oz",
    basePrice: 10.99,
    taxable: false,
    bagUnits: 0.35,
  },
  {
    key: "bounty-paper-towels",
    brand: "Bounty",
    name: "Select-A-Size Paper Towels 6 Count",
    normalizedName: "bounty select a size paper towels 6 count",
    searchAliases: ["paper towels", "bounty", "paper towel rolls"],
    category: "household",
    sizeValue: 6,
    sizeUnit: "ct",
    packageCount: 6,
    basePrice: 12.49,
    taxable: true,
    bagUnits: 1,
  },
  {
    key: "charmin-ultra-soft",
    brand: "Charmin",
    name: "Ultra Soft Toilet Paper 12 Count",
    normalizedName: "charmin ultra soft toilet paper 12 count",
    searchAliases: ["toilet paper", "charmin", "bath tissue"],
    category: "household",
    sizeValue: 12,
    sizeUnit: "ct",
    packageCount: 12,
    basePrice: 15.99,
    taxable: true,
    bagUnits: 1.2,
  },
  {
    key: "dawn-dish-soap",
    brand: "Dawn",
    name: "Ultra Dishwashing Liquid",
    normalizedName: "dawn ultra dishwashing liquid 24 oz",
    searchAliases: ["dish soap", "dishwashing liquid", "dawn soap"],
    category: "cleaning",
    sizeValue: 24,
    sizeUnit: "oz",
    basePrice: 4.99,
    taxable: true,
    bagUnits: 0.35,
  },
  {
    key: "tide-liquid-detergent",
    brand: "Tide",
    name: "Original Liquid Laundry Detergent",
    normalizedName: "tide original liquid laundry detergent 92 oz",
    searchAliases: ["laundry detergent", "tide detergent", "detergent"],
    category: "cleaning",
    sizeValue: 92,
    sizeUnit: "oz",
    basePrice: 14.99,
    taxable: true,
    bagUnits: 0.9,
  },
  {
    key: "colgate-toothpaste",
    brand: "Colgate",
    name: "Cavity Protection Toothpaste",
    normalizedName: "colgate cavity protection toothpaste 6 oz",
    searchAliases: ["toothpaste", "colgate toothpaste"],
    category: "personal-care",
    sizeValue: 6,
    sizeUnit: "oz",
    basePrice: 2.99,
    taxable: true,
    bagUnits: 0.2,
  },
  {
    key: "dove-body-wash",
    brand: "Dove",
    name: "Deep Moisture Body Wash",
    normalizedName: "dove deep moisture body wash 20 oz",
    searchAliases: ["body wash", "dove soap", "dove body wash"],
    category: "personal-care",
    sizeValue: 20,
    sizeUnit: "oz",
    basePrice: 7.99,
    taxable: true,
    bagUnits: 0.35,
  },
  {
    key: "pampers-diapers-size4",
    brand: "Pampers",
    name: "Swaddlers Diapers Size 4",
    normalizedName: "pampers swaddlers diapers size 4 66 count",
    searchAliases: ["diapers", "pampers size 4", "baby diapers"],
    category: "baby",
    sizeValue: 66,
    sizeUnit: "ct",
    packageCount: 66,
    basePrice: 29.99,
    taxable: true,
    bagUnits: 1.5,
  },
  {
    key: "huggies-wipes",
    brand: "Huggies",
    name: "Natural Care Baby Wipes",
    normalizedName: "huggies natural care baby wipes 168 count",
    searchAliases: ["baby wipes", "huggies wipes", "wipes"],
    category: "baby",
    sizeValue: 168,
    sizeUnit: "ct",
    packageCount: 168,
    basePrice: 8.99,
    taxable: true,
    bagUnits: 0.8,
  },
  {
    key: "purina-dog-food",
    brand: "Purina ONE",
    name: "Chicken and Rice Dog Food",
    normalizedName: "purina one chicken and rice dog food 16.5 lb",
    searchAliases: ["dog food", "purina dog food", "pet food"],
    category: "pet",
    sizeValue: 16.5,
    sizeUnit: "lb",
    basePrice: 24.99,
    taxable: true,
    bagUnits: 1.5,
  },
];

const storePricing: Record<string, { skuPrefix: string; multiplier: number }> = {
  "qfc-ballard": { skuPrefix: "0001111", multiplier: 1 },
  "fred-meyer-ballard": { skuPrefix: "0002222", multiplier: 0.97 },
};

function roundCurrency(value: number) {
  return Math.round(value * 100) / 100;
}

function buildProductsForStore(storeId: Store["id"]) {
  const storeConfig = storePricing[storeId];

  return seededCatalog
    .filter((seed) => !seed.stores || seed.stores.includes(storeId))
    .map((seed, index) => ({
      id: `${storeId}-${seed.key}`,
      storeId,
      sku: `${storeConfig.skuPrefix}${String(index + 1).padStart(5, "0")}`,
      brand: seed.brand,
      name: seed.name,
      normalizedName: seed.normalizedName,
      searchAliases: seed.searchAliases,
      category: seed.category,
      variant: seed.variant,
      sizeValue: seed.sizeValue,
      sizeUnit: seed.sizeUnit,
      packageCount: seed.packageCount,
      price: roundCurrency(seed.priceOverrides?.[storeId] ?? seed.basePrice * storeConfig.multiplier),
      taxable: seed.taxable,
      beverageTaxable: seed.beverageTaxable,
      bagUnits: seed.bagUnits,
    }) satisfies Product);
}

export const brandedCatalog = seededCatalog;

export const products: Product[] = stores
  .filter((store) => store.supportsPricing)
  .flatMap((store) => buildProductsForStore(store.id));

export const pricingRules: PricingRule[] = [
  {
    id: "wa-sales-tax-seattle",
    jurisdiction: "seattle-wa",
    ruleType: "sales_tax",
    effectiveStart: "2025-01-01",
    ruleJson: {
      rate: 0.1035,
    },
  },
  {
    id: "sea-sbt-standard",
    jurisdiction: "seattle-wa",
    ruleType: "sweetened_beverage_tax",
    effectiveStart: "2018-01-01",
    ruleJson: {
      ratePerOunce: 0.0175,
    },
  },
  {
    id: "sea-bag-fee-2026",
    jurisdiction: "seattle-wa",
    ruleType: "bag_fee",
    effectiveStart: "2026-01-01",
    ruleJson: {
      paper: 0.08,
      reusablePlastic: 0.12,
    },
  },
];

export const sampleZipCoordinates: Record<string, { lat: number; lng: number; label: string }> = {
  "98107": { lat: 47.6687, lng: -122.3868, label: "Ballard" },
  "98103": { lat: 47.6601, lng: -122.3437, label: "Fremont" },
  "98109": { lat: 47.6273, lng: -122.3451, label: "South Lake Union" },
  "98115": { lat: 47.6844, lng: -122.3003, label: "Wedgwood" },
};
